# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0003_auto_20160601_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(default='PLN', max_length=3, verbose_name='currency code'),
        ),
    ]
